version: "3"

services:
  dev_postgres:
    image: postgres:11-alpine
    container_name: dev_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
